Feat/error operators
TechNobre/PowerUtils.Results pull request #32
Opened 2022-11-26 19:56 UTC by NelsonBN

## Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] Implemented tests for new features.
- [x] I tested the features already implemented.
- [x] Added usage examples in the readme.

2022-11-26 19:59 UTC, NelsonBN reviewed
All OK

2022-11-26 20:32 UTC, NelsonBN reviewed
Code smell fixed

2022-11-27 15:04 UTC, filipe11402 requested changes
Minor Questions made.
All Good aside from that

2022-11-27 18:29 UTC, NelsonBN commented on src/CommonUtils.cs
> +            if(error.Code != other.Code)
I agree with you. Updated it

2022-11-27 18:29 UTC, NelsonBN commented on src/CommonUtils.cs
> +            if(error.Description != other.Description)
I agree with you. Updated it

2022-11-27 22:26 UTC, filipe11402 approved these changes
All Ok

2022-11-27 22:41 UTC, merged

2022-11-27 22:42 UTC, NelsonBN commented
:tada: This PR is included in version 2.5.0 :tada:

The release is available on [GitHub release](https://github.com/TechNobre/PowerUtils.Results/releases/tag/v2.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: